baseURL = "https://www.ytpor.com"
languageCode = "en-us"
title = "YT Por"
theme = "PaperMod"
googleAnalytics = 'G-3V2PB7JNZW'

[params]
ShowCodeCopyButtons = true
ShowShareButtons = true
ShowPostNavLinks = true

[params.homeInfoParams]
Title = "YT Por"
Content = "I’m a code writer, observer, handyman, researcher, motivator, consultant and photographer."

[[params.socialIcons]]
name = "github"
url = "https://github.com/ytpor/"
weight = 1

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/yt-por-081243aa/"
weight = 3

[outputs]
home = ["HTML", "RSS", "JSON"]

[menu]

[[menu.main]]
name = 'About'
url = '/about/'
weight = 30

[[menu.main]]
name = 'Archives'
url = '/archives/'
weight = 40

[[menu.main]]
name = 'Search'
url = '/search/'
weight = 45

[[menu.main]]
name = 'Tags'
url = '/tags/'
weight = 50
